-- A list of all the students

SELECT * FROM STUDENTS;

-- A list of all the trainers

SELECT * FROM TRAINERS;

-- A list of all the assignments

SELECT * FROM ASSIGNMENTS;

-- A list of all the courses

SELECT * FROM COURSES;

-- All the students per course

SELECT C.TITLE,C.STREAM,C.TYPE,S.FIRST_NAME,S.LAST_NAME
FROM STUDENTS S
JOIN STUDENT_COURSE SC
ON S.STUD_ID=SC.STUD_ID
JOIN COURSES C
ON SC.COURSE_ID=C.COURSE_ID;

-- All the trainers per course

SELECT C.TITLE,C.STREAM,C.TYPE,T.FIRST_NAME,T.LAST_NAME
FROM TRAINERS T
JOIN TRAINER_COURSE TC
ON T.TRAINER_ID=TC.TRAINER_ID
JOIN COURSES C
ON TC.COURSE_ID=C.COURSE_ID;

-- All the assignments per course

SELECT C.TITLE,C.STREAM,C.TYPE,A.TITLE,A.DESCRIPTION,CA.ASSI_SUB_DATE_TIME
FROM ASSIGNMENTS A
JOIN COURSE_ASSIGNMENT CA
ON A.ASSIGNMENT_ID=CA.ASSIGNMENT_ID
JOIN COURSES C
ON CA.COURSE_ID=C.COURSE_ID;

-- All the assignments per course per student

SELECT C.TITLE,C.STREAM,C.TYPE,S.FIRST_NAME,S.LAST_NAME,A.TITLE,A.DESCRIPTION,CA.ASSI_SUB_DATE_TIME
FROM COURSE_STUDENT_ASSIGNMENT CSA
JOIN STUDENTS S
ON S.STUD_ID=CSA.STUD_ID
JOIN COURSES C
ON CSA.COURSE_ID=C.COURSE_ID
JOIN ASSIGNMENTS A
ON CSA.ASSIGNMENT_ID=A.ASSIGNMENT_ID
JOIN COURSE_ASSIGNMENT CA
ON CA.COURSE_ID=C.COURSE_ID AND CA.ASSIGNMENT_ID=A.ASSIGNMENT_ID;

-- A list of students that belong to more than one courses

SELECT S.FIRST_NAME,S.LAST_NAME,S.DATE_OF_BIRTH,COUNT(*) AS COURSES
FROM STUDENTS S
JOIN STUDENT_COURSE SC
ON S.STUD_ID=SC.STUD_ID
GROUP BY SC.STUD_ID
HAVING COURSES>1